## 「[ゼロから作るDeep Learning ❸――フレームワーク編](https://www.oreilly.co.jp/books/9784873119069/)」を元にPythonの基礎解説 第5最終ステージ
この記事では、前回に続けてPythonの基礎解説を行なっていきます。DeZero、NumPy、CuPyについては詳細な説明は行いません。

## 「第5ステージ DeZeroで挑む」より
第5ステージでは、DeZeroに、GPUでの実行、モデルの外部ファイルへの保存、学習時とテスト時で挙動を変えるレイヤ（Dropoutなど）などの機能、CNN、RNN、LSTMなどが実装される。

### 「ステップ52 GPU対応」

### 「ステップ53 モデルの保存と読み込み」より
 - モデルの保存と読み込みをNumPyの`np.save`、`np.savez`、`np.savez_compressed`、`np.load`を使って行う。
   - [numpy.save — NumPy v1.19 Manual](https://numpy.org/doc/stable/reference/generated/numpy.save.html)
   - [numpy.savez — NumPy v1.19 Manual](https://numpy.org/doc/stable/reference/generated/numpy.savez.html)
   - [numpy.savez_compressed — NumPy v1.19 Manual](https://numpy.org/doc/stable/reference/generated/numpy.savez_compressed.html)
   - [numpy.load — NumPy v1.19 Manual](https://numpy.org/doc/stable/reference/generated/numpy.load.html)

### 「ステップ54 Dropoutとテストモード」より
 - Direct DropoutとInverted Dropoutの解説。DeZeroではInverted Dropoutを採用。

### 「ステップ55 CNNのメカニズム（1）」より
 - CNNによってなぜ画像認識が上手くできるのか、なぜ画像の特徴量を抽出できるのか、といったことについては『ゼロから作るDeep Learning』などを参照。
 - DeZeroでは出力サイズを求める`get_conv_outsize`関数を提供。
 - `出力サイズ = 入力データサイズ  + 2 * パディングサイズ - カーネルサイズ // ストライドサイズ + 1`
   - `//`：小数点以下切り捨ての割り算

### 「ステップ56 CNNのメカニズム（2）」

### 「ステップ57 conv2d関数とpooling関数」より
 - DeZeroの`im2col`関数では、入力データからカーネル適用部分を取り出し`reshape`で一列にして、行列にするところまで行う。カーネルからも行列を作り行列積により計算できる。`to_matrix`フラグを`False`にすれば`respape`を省略して、NumPyの`np.tensordot`、`np.einsum`によりテンソル積の計算で行うこともできる。詳細は書籍参照。
 - NumPyの`reshape`関数の引数に`-1`を指定すると、多次元配列の要素数の辻褄が合うように要素をまとめてくれる。
   - [numpy.reshape — NumPy v1.19 Manual](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html), [numpy.ndarray.reshape](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html)

In [1]:
import numpy as np

a = np.array([[1,2,3], [4,5,6]])
b = np.reshape(a, (3,-1)) # -1を2にされる。
print(b)
c = b.reshape((2, -1)) # -1を3にされる。
print(c) # 最初に戻る

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


### 「ステップ58 代表的なCNN（VGG16）」より
 - DeZeroのVGG,[arXiv:1409.1556](https://arxiv.org/abs/1409.1556)の実装。学習済み重み読み込みも実装。ResNetも実装。
 - 画像処理のライブラリPIL（Python Image Library）のインストールは、`pip install pillow`。Anacondaはインストール済み。
 - NumPyの`ndarray`への次元追加削除の参考：[NumPy配列ndarrayに次元を追加するnp.newaxis, np.expand_dims() | note.nkmk.me
](https://note.nkmk.me/python-numpy-newaxis/)

### 「ステップ59 RNNによる時系列データ処理」より
 - DeZeroに`RNN`レイヤが実装され、サイン波の学習が実装される。

### 「ステップ60 LSTMとデータローダ」より（最終ステップ！）
 - DeZeroに時系列用のデータローダ`SeqDataLoader`が実装され、`LSTM`レイヤが実装される。サイン波の学習がかなり改善している。
 - LSTMの詳しい説明は、『ゼロから作るDeep Learning ❷』の「6章ゲート付きRNN」参照。