## 「ゼロから作るDeep Learning ❸――フレームワーク編」を元にPythonの基礎解説1
[ゼロから作るDeep Learning ❸――フレームワーク編](https://www.oreilly.co.jp/books/9784873119069/)は、PyTorch同様のDefine-by-RunスタイルのDeep Learning[深層学習]フレームワークDeZeroをゼロから60ステップで段階的に開発していく内容で、Pythonのエッセンスから詳しく解説されています。

「ゼロから作るDeep Learning」シリーズの３冊目ですが、この本を最初に読んでも十分に理解できると思います。

個人的なPythonの実装方針と近いこともあり、[ゼロから作るDeep Learning ❸――フレームワーク編](https://www.oreilly.co.jp/books/9784873119069/)を参考にしてPythonの基礎解説と雛形の作成を行なっていきます。

この記事では、DeZeroやNumPyについては詳細な説明は行いません。

### 「ゼロから作るDeep Learning ❸――フレームワーク編」の参考文献
 - [O'Reilly Japan - ゼロから作るDeep Learning ❸](https://www.oreilly.co.jp/books/9784873119069/)
 - [ゼロから作るDeep Learning ❸ ―フレームワーク編｜Amazon](https://www.amazon.co.jp/dp/4873119065/)
 - [「ゼロから作るDeep Learning ❸」オンラインブック](https://koki0702.github.io/dezero-book/index.html)
   - 「第1ステージ 微分を自動で求める」の10ステップが書かれてます。
 - [GitHub - oreilly-japan/deep-learning-from-scratch-3](https://github.com/oreilly-japan/deep-learning-from-scratch-3)
   - DeZeroのGitHubです。

キィットキィトは、Anaconda Individual EditionのPython 3.7版でPythonをインストールしています。

### Pythonの参考文献
 - [Anaconda | Individual Edition](https://www.anaconda.com/products/individual)
 - [Python3ドキュメント](https://docs.python.org/ja/3/)
   - [組み込み例外](https://docs.python.org/ja/3/library/exceptions.html)
   - [unittest --- ユニットテストフレームワーク](https://docs.python.org/ja/3/library/unittest.html)
 - [NumPy](https://numpy.org/)
 - [Travis CI](https://travis-ci.org/)
   - 継続的インテグレーションサービス

コーディング規約は、Pythonの標準ライブラリでも採用されている一般的なコーディング規約であるPEP8に従います。

### 「PEP」の参考文献
 - [PEP（Python Enhancement Proposal）](https://www.python.org/dev/peps/)
 - [PEP8 日本語版](https://github.com/mumumu/pep8-ja)
 - [pep8-ja](https://pep8-ja.readthedocs.io)



## 「第1ステージ 微分を自動で求める」より
「第1ステージ」では、入出力が１つの単純なDeep Learningネットワークのバックプロパゲーションまで解説されています。

### 「ステップ1 箱としての変数」より
 - クラス名はPEP8に従い大文字で始める。
 - クラスのインスタンス[オブジェクト]生成・初期化はコンストラクタとも呼ばれる特殊メソッド[関数]`__init__`に記述する。
 - NumPyの多次元配列のクラス`numpy.ndarray`のインスタンスを`np.array`関数で生成する。
 - `numpy.ndarray`の`ndim`インスタンス変数は配列の次元を表す。`shape`インスタンス変数により多次元配列の形状が取得できる。
   - 0次元の配列はスカラ、1次元の配列はベクトル、2次元の配列は行列、N次元の配列はN階のテンソルと呼ばれる。

In [1]:
class Vehicle:
    def __init__(self, velocity):
        self.velocity = velocity

import numpy as np

veh = Vehicle(10)
print(veh.velocity)

vec = np.array([1.0, 2.0, 3.0]) # ベクトル
print(vec)
print(vec.ndim)
print(vec.shape)
mat = np.array([[1, 2, 3], [4, 5, 6]]) # 行列
print(mat)
print(mat.ndim)
print(mat.shape)

10
[1. 2. 3.]
1
(3,)
[[1 2 3]
 [4 5 6]]
2
(2, 3)


### 「ステップ2 変数を生み出す関数」より
 - クラスのインスタンスに引数を渡すことで特殊メソッド`__call__`が呼ばれる。
 - `type`関数により型が取得できる。
 - 親クラスの子クラスへの継承は、`子クラス(親クラス)`のように定義する。子クラスでは親クラスのメソッドが引き継がれる。
 - 組み込み例外`NotImplementedError`は未実装であることを表す。

In [2]:
class Vehicle:
    def __init__(self, velocity):
        self.velocity = velocity

    def __call__(self, velocity):
        self.velocity += velocity

    def run(self):
        raise NotImplementedError()


class Car(Vehicle):
    def run(self):
        print('Run at {}.'.format(self.velocity))


veh = Vehicle(5)
# veh.run() # raise NotImplementedError()

car = Car(10)
car.run()

car(veh.velocity)
car.run()

print(type(Vehicle))
print(type(veh))
print(type(car))

Run at 10.
Run at 15.
<class 'type'>
<class '__main__.Vehicle'>
<class '__main__.Car'>


### 「ステップ3 関数の連結」より
 - 引数と返り値が同じ型の関数は連結して呼べる。連結した関数を合成関数と呼ぶ。

In [3]:
class Vehicle:
    def __init__(self, velocity):
        self.velocity = velocity

    def __call__(self, vehicle): # ここを変更
        self.velocity += vehicle.velocity
        return self 

    def run(self):
        raise NotImplementedError()


class Car(Vehicle):
    def run(self):
        print('Run at {}.'.format(self.velocity))


veh = Vehicle(1)

car = Car(10)
car.run()

car(car(veh))
car.run()

Run at 10.
Run at 22.


### 「ステップ4 数値微分」
### 「ステップ5 バックプロパゲーションの理論」
### 「ステップ6 手作業によるバックプロパゲーション」
### 「ステップ7 バックプロパゲーションの自動化」より
 - assert文`assert ...`で`...`が`True`でない場合は例外が発生する。
 - 関数Fから関数Fを呼び出すと関数Fが再帰的に呼び出される。

In [4]:
class Vehicle:
    def __init__(self, velocity):
        self.velocity = velocity

    def __call__(self, veh):
        self.velocity += veh.velocity
        return self 

    def run(self):
        raise NotImplementedError()


class Car(Vehicle):
    def run(self):
        print('Run at {}.'.format(self.velocity))
        self.velocity -= 1
        if self.velocity > 0:
            self.run() # 再帰

car = Car(10)
car.run()
assert car.velocity == 0

Run at 10.
Run at 9.
Run at 8.
Run at 7.
Run at 6.
Run at 5.
Run at 4.
Run at 3.
Run at 2.
Run at 1.


### 「ステップ8 再帰からループへ」
 - リストの`pop`関数で指定位置（デフォルトは最後）の要素を削除しその要素を取り出す。
### 「ステップ9 関数をより便利に」より
 - `np.ones_like()`により、引数と同じ形状・同じデータ型で、要素が`1`の`ndarray`インスタンスを生成する。
 - `isinstance(1st, 2nd)`は、引数1stインスタンスが、引数2ndかそのサブクラス型のインスタンスであればTrueを返す関数。引数2ndはタプル()にして複数の型を指定することもできる。
 - 組み込み例外`TypeError`は型の例外を表す。

In [5]:
class Vehicle:
    def __init__(self, velocity):
        if velocity is not None:
            if not isinstance(velocity, int):
                message = '{} is not supported'
                raise TypeError(message.format(type(velocity)))
        self.velocity = velocity

    def __call__(self, veh):
        self.velocity += veh.velocity
        return self 

    def run(self):
        raise NotImplementedError()


class Car(Vehicle):
    def run(self):
        print('Run at {}.'.format(self.velocity))
        self.velocity -= 1
        if self.velocity > 0:
            self.run()

import numpy as np
dat_list = [1.0, 2.0, 3.0]
print(dat_list.pop())
data = np.array(dat_list)
print(np.ones_like(data))

car = Car(10)
car2 = Car(1.5) # TypeError

3.0
[1. 1.]


TypeError: <class 'float'> is not supported

### 「ステップ10 テストを行う」より
 - Python標準ライブラリの`unittest`でテストを行う。
 - `Car`クラスの関数をテストする場合`unittest`をインポートし、`unittest.TestCase`を継承する`CarTest`クラスにテストを実装する。テストは、名前が`test`ではじまる関数の中に書く。
 - `unittest`にはテスト用の関数`self.assertEqual`、`self.assertGreater`、`self.assertTrue`などが用意されている。
   - 詳細は[unittest --- ユニットテストフレームワーク](https://docs.python.org/ja/3/library/unittest.html)を参照。
 - `python`コマンドに`-m unittest`引数を与えて、テストモードでPython ファイルを実行する。また、`discover`サブコマンドの後に指定したディレクトリからテストファイル（`test*.py`）を探索し、見つかったすべてのファイルをまとめて実行できる。
 - キィットキィトの`basic`リポジトリをダウンロード（`clone`）して`unittest`できる。説明はステップ23の解説で行う。

```
$ git clone https://github.com/qitqito/basic.git
$ cd basic
$ python -m unittest discover tests
```

 - DeZeroのGitHubリポジトリは、[Travis CI](https://travis-ci.org/)という継続的インテグレーションのサービスと連携していて、DeZeroのGitHubリポジトリで、コードを`push`したり、`Pull Request`をマージしたりしたタイミングで、自動でテストが実行されるようになっているとのこと。キィットキィトもTravis CIと連携している。

In [6]:
class Vehicle:
    def __init__(self, velocity):
        if velocity is not None:
            if not isinstance(velocity, int):
                raise TypeError('{} is not supported'.format(type(velocity)))
        self.velocity = velocity

    def __call__(self, vehicle):
        self.velocity += vehicle.velocity
        return self 

    def run(self):
        raise NotImplementedError()


class Car(Vehicle):
    def run(self):
        print('Run at {}.'.format(self.velocity))
        self.velocity -= 1
        if self.velocity > 0:
            self.run()

import unittest

class CarTest(unittest.TestCase):
    def test_run(self):
        car = car(10)
        self.assertEqual(car.velocity, 10)